version: "3.5"

include:
    # Services
    - ../svc/backtests/deployments/docker-compose.yaml
    - ../svc/candlesticks/deployments/docker-compose.yaml
    - ../svc/exchanges/deployments/docker-compose.yaml
    - ../svc/indicators/deployments/docker-compose.yaml
    - ../svc/ticks/deployments/docker-compose.yaml
    # Tools
    - ../tools/uptrace/docker-compose.yaml

services:
    nats:
        image: nats
        ports:
            - 4222:4222
        networks:
            - cryptellation

volumes:
    gocache:
    gobuild:


networks:
    cryptellation:
