version: '3'
services:
  cockroachdb:
    image: cockroachdb/cockroach
    ports:
        - 26257:26257
        - 26256:8080
    networks:
        - cryptellation-network
    ulimits:
        nofile:
            soft: 65536
            hard: 65536
    command: start-single-node --insecure
    restart: unless-stopped
    volumes:
          - ./services/candlesticks/configs/candlesticks.sql:/docker-entrypoint-initdb.d/candlesticks.sql
          - ./services/exchanges/configs/exchanges.sql:/docker-entrypoint-initdb.d/exchanges.sql
  nats:
    image: nats:alpine
    hostname: nats
    networks:
        - cryptellation-network
  exchanges:
    build:
      context: services/exchanges
      dockerfile: build/package/Dockerfile
    volumes:
      - .:/code
      - /root/.cache/go-build
    working_dir: /code
    ports:
      - 127.0.0.1:9002:9002
    env_file:
      - .env
    environment:
      - COCKROACHDB_DATABASE=exchanges
      - SERVICE_PORT=9002
    depends_on:
      - cockroachdb
    networks:
      - cryptellation-network
  candlesticks:
    build:
      context: services/candlesticks
      dockerfile: build/package/Dockerfile
    volumes:
      - .:/code
      - /root/.cache/go-build
    working_dir: /code
    ports:
      - 127.0.0.1:9003:9003
    env_file:
      - .env
    environment:
      - COCKROACHDB_DATABASE=candlesticks
      - SERVICE_PORT=9003
    depends_on:
      - cockroachdb
    networks:
      - cryptellation-network
  backtests-redis:
    image: redis:alpine
    hostname: redis
    networks:
        - cryptellation-network
  backtests:
    build:
      context: services/backtests
      dockerfile: build/package/Dockerfile
    volumes:
      - .:/code
      - /root/.cache/go-build
    working_dir: /code
    ports:
      - 127.0.0.1:9004:9004
    env_file:
      - .env
    environment:
      - REDIS_URL=backtests-redis:6379
      - SERVICE_PORT=9004
    depends_on:
      - backtests-redis
      - nats
      - candlesticks
    networks:
      - cryptellation-network
  ticks-redis:
    image: redis:alpine
    hostname: redis
    networks:
        - cryptellation-network
  ticks:
    build:
      context: services/ticks
      dockerfile: build/package/Dockerfile
    volumes:
      - .:/code
      - /root/.cache/go-build
    working_dir: /code
    ports:
      - 127.0.0.1:9005:9005
    env_file:
      - .env
    environment:
      - REDIS_URL=ticks-redis:6379
      - SERVICE_PORT=9005
    depends_on:
      - ticks-redis
      - nats
    networks:
      - cryptellation-network
  livetests-redis:
    image: redis:alpine
    hostname: redis
    networks:
        - cryptellation-network
  livetests:
    build:
      context: services/livetests
      dockerfile: build/package/Dockerfile
    volumes:
      - .:/code
      - /root/.cache/go-build
    working_dir: /code
    ports:
      - 127.0.0.1:9006:9006
    env_file:
      - .env
    environment:
      - REDIS_URL=livetests-redis:6379
      - SERVICE_PORT=9006
    depends_on:
      - livetests-redis
    networks:
      - cryptellation-network
networks:
    cryptellation-network:
