# Specific section for dependencies
cockroachdb:
  enabled: true
  statefulset:
    resources:
      limits:
        cpu: 100m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 512Mi
    securityContext:
      enabled: false
  init:
    provisioning:
      enabled: true
    securityContext:
      enabled: false
  securityContext:
    enabled: false
  tls:
    enabled: false
nats:
  enabled: true

# Specific section for credentials
credentials:
  exchanges:
    binance:
      api_key:
      secret_key:
  event_brokers:
    nats:
      host: "{{ .Release.Name }}-nats.{{ .Release.Namespace }}.svc.cluster.local"
      port: 4222
  datastores:
    sqldb:
      host: "{{ .Release.Name }}-cockroachdb-public.{{ .Release.Namespace }}.svc.cluster.local"
      port: 26257
      user: root
      password:

# Specific section for services
services:
  image:
    repository: lerenn/cryptellation
    tag: 0.8.2
    pullPolicy: Always
  backtests:
    sqldb:
      database: backtests
    health:
      port: 9000
  candlesticks:
    sqldb:
      database: candlesticks
    health:
      port: 9000
  exchanges:
    sqldb:
      database: exchanges
    health:
      port: 9000
  ticks:
    sqldb:
      database: ticks
    health:
      port: 9000
