# Specific section for dependencies
cockroachdb:
  enabled: true
  statefulset:
    resources:
      limits:
        cpu: 100m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 512Mi
    securityContext:
      enabled: false
  init:
    provisioning:
      enabled: true
    securityContext:
      enabled: false
  securityContext:
    enabled: false
  tls:
    enabled: false
nats:
  enabled: true

# Specific section for credentials
credentials:
  exchanges:
    binance:
      api_key:
      secret_key:
  event_brokers:
    nats:
      host: "{{ .Release.Name }}-nats.{{ .Release.Namespace }}.svc.cluster.local"
      port: 4222
  datastores:
    sqldb:
      host: "{{ .Release.Name }}-cockroachdb-public.{{ .Release.Namespace }}.svc.cluster.local"
      port: 26257
      user: root
      password:
  opentelemetry:
    grpc:
      endpoint:

# Specific section for services
services:
  backtests:
    image:
      repository: lerenn/cryptellation-backtests
      tag: latest
      pullPolicy: Always
    sqldb:
      database: backtests
    health:
      port: 9000
  candlesticks:
    image:
      repository: lerenn/cryptellation-candlesticks
      tag: latest
      pullPolicy: Always
    sqldb:
      database: candlesticks
    health:
      port: 9000
  exchanges:
    image:
      repository: lerenn/cryptellation-exchanges
      tag: latest
      pullPolicy: Always
    sqldb:
      database: exchanges
    health:
      port: 9000
  indicators:
    image:
      repository: lerenn/cryptellation-indicators
      tag: latest
      pullPolicy: Always
    sqldb:
      database: indicators
    health:
      port: 9000
  ticks:
    image:
      repository: lerenn/cryptellation-ticks
      tag: latest
      pullPolicy: Always
    sqldb:
      database: ticks
    health:
      port: 9000

# Specific debug section
debug: 
  forceDeployment: false
