# Specific section for dependencies

mongodb:
  enabled: true
  image:
    repository: zcube/bitnami-compat-mongodb
    tag: latest
  auth:
    enabled: false
nats:
  enabled: true

# Specific section for credentials
credentials:
  exchanges:
    binance:
      api_key:
      secret_key:
  event_brokers:
    nats:
      host: "{{ .Release.Name }}-nats.{{ .Release.Namespace }}.svc.cluster.local"
      port: 4222
  datastores:
    mongodb:
      connection_string: "mongodb://{{ .Release.Name }}-mongodb.{{ .Release.Namespace }}.svc.cluster.local:27017"
  opentelemetry:
    grpc:
      endpoint:

# Specific section for services
services:
  backtests:
    image:
      repository: lerenn/cryptellation-backtests
      tag: v1.12.0
      pullPolicy: Always
    mongodb:
      database: backtests
    health:
      port: 9000
  candlesticks:
    image:
      repository: lerenn/cryptellation-candlesticks
      tag: v1.12.0
      pullPolicy: Always
    mongodb:
      database: candlesticks
    health:
      port: 9000
  exchanges:
    image:
      repository: lerenn/cryptellation-exchanges
      tag: v1.12.0
      pullPolicy: Always
    mongodb:
      database: exchanges
    health:
      port: 9000
  forwardtests:
    image:
      repository: lerenn/cryptellation-forwardtests
      tag: v1.12.0
      pullPolicy: Always
    mongodb:
      database: forwardtests
    health:
      port: 9000
  indicators:
    image:
      repository: lerenn/cryptellation-indicators
      tag: v1.12.0
      pullPolicy: Always
    mongodb:
      database: indicators
    health:
      port: 9000
  ticks:
    image:
      repository: lerenn/cryptellation-ticks
      tag: v1.12.0
      pullPolicy: Always
    mongodb:
      database: ticks
    health:
      port: 9000

# Specific debug section
debug: 
  forceDeployment: false
