apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backtests
  name: backtests
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backtests
  strategy: {}
  template:
    metadata:
      labels:
        app: backtests
    spec:
      containers:
      - name: backtests
        image: {{ .Values.services.backtests.image }}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /liveness
            port: {{ (.Values.services.backtests.health).port | default 9000 }}
        readinessProbe:
          httpGet:
            path: /readiness
            port: {{ (.Values.services.backtests.health).port | default 9000 }}
        command: [ "cryptellation-backtests", "serve" ]
        env:
        {{- include "common.env" "backtests" | indent 8 }}
        resources: {}
      initContainers:
      {{- include "dependencies.cockroachdb.init-container" . | indent 6 }}
      - name: init-sql-database
        image: {{ .Values.services.backtests.image }}
        command: [ "cryptellation-backtests", "migrations", "migrate" ]
        env:
        {{- include "common.env" "backtests" | indent 8 }}
      volumes:
        {{- include "dependencies.cockroachdb.volumes" . | indent 8 }}
status: {}
