apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backtests
  name: backtests
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backtests
  strategy: {}
  template:
    metadata:
      annotations:
        {{if (.Values.debug).forceDeployment }}timestamp: {{ now | quote }}{{end}}
      labels:
        app: backtests
    spec:
      containers:
      - name: backtests
        image: {{ ((.Values.services).backtests).image.repository | default "lerenn/cryptellation-backtests" }}:{{ ((.Values.services).backtests).image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ ((.Values.services).backtests).image.pullPolicy | default "Always" }}
        livenessProbe:
          httpGet:
            path: /liveness
            port: {{ (((.Values.services).backtests).health).port | default 9000 }}
        readinessProbe:
          httpGet:
            path: /readiness
            port: {{ (((.Values.services).backtests).health).port | default 9000 }}
        env:
        {{- include "common.env" "backtests" | indent 8 }}
        resources: {}
status: {}
