apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: candlesticks
  name: candlesticks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: candlesticks
  strategy: {}
  template:
    metadata:
      labels:
        app: candlesticks
    spec:
      containers:
      - name: candlesticks
        image: {{ .Values.services.candlesticks.image }}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /liveness
            port: {{ .Values.services.candlesticks.health.port | default 9000 }}
        readinessProbe:
          httpGet:
            path: /readiness
            port: {{ .Values.services.candlesticks.health.port | default 9000 }}
        command: [ "cryptellation-candlesticks", "serve" ]
        env:
        - name: "BINANCE_API_KEY"
          valueFrom:
            configMapKeyRef:
              key: binance.api_key
              name: cryptellation-credentials
        - name: "BINANCE_SECRET_KEY"
          valueFrom:
            configMapKeyRef:
              key: binance.secret_key
              name: cryptellation-credentials
        - name: "HEALTH_PORT"
          valueFrom:
            configMapKeyRef:
              key:  candlesticks.health.port
              name: cryptellation-config
        - name: "NATS_HOST"
          valueFrom:
            configMapKeyRef:
              key:  nats.host
              name: cryptellation-credentials
        - name: "NATS_PORT"
          valueFrom:
            configMapKeyRef:
              key:  nats.port
              name: cryptellation-credentials
        - name: "SQLDB_USER"
          valueFrom:
            configMapKeyRef:
              key:  sqldb.user
              name: cryptellation-credentials
        - name: "SQLDB_PASSWORD"
          valueFrom:
            configMapKeyRef:
              key:  sqldb.password
              name: cryptellation-credentials
        - name: "SQLDB_HOST"
          valueFrom:
            configMapKeyRef:
              key:  sqldb.host
              name: cryptellation-credentials
        - name: "SQLDB_PORT"
          valueFrom:
            configMapKeyRef:
              key:  sqldb.port
              name: cryptellation-credentials
        - name: "SQLDB_DATABASE"
          valueFrom:
            configMapKeyRef:
              key:  candlesticks.sqldb.database
              name: cryptellation-config
        resources: {}
      initContainers:
      - name: init-candlesticks-sqldb
        image: {{ .Values.services.candlesticks.image }}
        command: [ "cryptellation-candlesticks", "migrations", "migrate" ]
        env:
        - name: "SQLDB_USER"
          valueFrom:
            configMapKeyRef:
              key:  sqldb.user
              name: cryptellation-credentials
        - name: "SQLDB_PASSWORD"
          valueFrom:
            configMapKeyRef:
              key:  sqldb.password
              name: cryptellation-credentials
        - name: "SQLDB_HOST"
          valueFrom:
            configMapKeyRef:
              key:  sqldb.host
              name: cryptellation-credentials
        - name: "SQLDB_PORT"
          valueFrom:
            configMapKeyRef:
              key:  sqldb.port
              name: cryptellation-credentials
        - name: "SQLDB_DATABASE"
          valueFrom:
            configMapKeyRef:
              key:  candlesticks.sqldb.database
              name: cryptellation-config
status: {}
