apiVersion: v1
kind: ConfigMap
metadata:
    name: cryptellation-config
data:
    # Backtests
    backtests.mongodb.database: "{{ (((.Values.services).backtests).sqldb).database | default "backtests" }}"
    backtests.health.port: "{{ (((.Values.services).backtests).health).port | default 9000 }}"

    # Candlesticks
    candlesticks.mongodb.database: "{{ (((.Values.services).candlesticks).sqldb).database | default "candlesticks" }}"
    candlesticks.health.port: "{{ (((.Values.services).candlesticks).health).port | default 9000 }}"

    # Exchanges
    exchanges.mongodb.database: "{{ (((.Values.services).exchanges).sqldb).database | default "exchanges" }}"
    exchanges.health.port: "{{ (((.Values.services).exchanges).health).port | default 9000 }}"

    # Forwardtests
    forwardtests.mongodb.database: "{{ (((.Values.services).forwardtests).sqldb).database | default "forwardtests" }}"
    forwardtests.health.port: "{{ (((.Values.services).forwardtests).health).port | default 9000 }}"

    # Indicators
    indicators.mongodb.database: "{{ (((.Values.services).indicators).sqldb).database | default "indicators" }}"
    indicators.health.port: "{{ (((.Values.services).indicators).health).port | default 9000 }}"

    # Ticks
    ticks.mongodb.database: "{{ (((.Values.services).ticks).sqldb).database | default "ticks" }}"
    ticks.health.port: "{{ (((.Values.services).ticks).health).port | default 9000 }}"
