apiVersion: v1
kind: ConfigMap
metadata:
    name: cryptellation-credentials
data:
    # Exchanges
    binance.api_key: "{{ (.Values.credentials).exchanges.binance.api_key }}"
    binance.secret_key: "{{ (.Values.credentials).exchanges.binance.secret_key }}"

    # Event brokers
    {{ $DEFAULT_NATS_HOST := (print .Release.Name "-nats." .Release.Namespace ".svc.cluster.local") }}
    nats.host: "{{ ((.Values.credentials).event_brokers).nats.host | default $DEFAULT_NATS_HOST }}"
    nats.port: "{{ ((.Values.credentials).event_brokers).nats.port | default 4222 }}"

    # Datastores
    {{ $DEFAULT_SQLDB_HOST := (print .Release.Name "-cockroachdb-public." .Release.Namespace ".svc.cluster.local") }}
    sqldb.host: "{{ ((.Values.credentials).datastores).sqldb.host | default $DEFAULT_SQLDB_HOST }}"
    sqldb.port: "{{ ((.Values.credentials).datastores).sqldb.port | default 26257 }}"
    sqldb.user: "{{ ((.Values.credentials).datastores).sqldb.user | default "root" }}"
    sqldb.password: "{{ ((.Values.credentials).datastores).sqldb.password }}"
