apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: exchanges
  name: exchanges
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exchanges
  strategy: {}
  template:
    metadata:
      annotations:
        {{if (.Values.debug).forceDeployment }}timestamp: {{ now | quote }}{{end}}
      labels:
        app: exchanges
    spec:
      initContainers:
      {{- include "dependencies.cockroachdb.init-container" . | indent 6 }}
      - name: init-sql-database
        image: {{ (.Values.services).image.repository | default "lerenn/cryptellation" }}:{{ (.Values.services).image.tag | default "latest" }}
        imagePullPolicy: {{ (.Values.services).image.pullPolicy | default "Always" }}
        command: [ "cryptellation-exchanges", "migrations", "migrate" ]
        env:
        {{- include "common.env" "exchanges" | indent 8 }}
      containers:
      - name: exchanges
        image: {{ (.Values.services).image.repository | default "lerenn/cryptellation" }}:{{ (.Values.services).image.tag | default "latest" }}
        imagePullPolicy: {{ (.Values.services).image.pullPolicy | default "Always" }}
        livenessProbe:
          httpGet:
            path: /liveness
            port: {{ (((.Values.services).exchanges).health).port | default 9000 }}
        readinessProbe:
          httpGet:
            path: /readiness
            port: {{ (((.Values.services).exchanges).health).port | default 9000 }}
        command: [ "cryptellation-exchanges", "serve" ]
        env:
        - name: "BINANCE_API_KEY"
          valueFrom:
            configMapKeyRef:
              key: binance.api_key
              name: cryptellation-credentials
        - name: "BINANCE_SECRET_KEY"
          valueFrom:
            configMapKeyRef:
              key: binance.secret_key
              name: cryptellation-credentials
        {{- include "common.env" "exchanges" | indent 8 }}
        resources: {}
      volumes:
        {{- include "dependencies.cockroachdb.volumes" . | indent 8 }}
status: {}
