apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: indicators
  name: indicators
spec:
  replicas: 1
  selector:
    matchLabels:
      app: indicators
  strategy: {}
  template:
    metadata:
      annotations:
        {{if (.Values.debug).forceDeployment }}timestamp: {{ now | quote }}{{end}}
      labels:
        app: indicators
    spec:
      containers:
      - name: indicators
        image: {{ ((.Values.services).indicators).image.repository | default "lerenn/cryptellation-indicators" }}:{{ ((.Values.services).indicators).image.tag | default (printf "v%s" .Chart.AppVersion) }}
        imagePullPolicy: {{ ((.Values.services).indicators).image.pullPolicy | default "Always" }}
        livenessProbe:
          httpGet:
            path: /liveness
            port: {{ (((.Values.services).indicators).health).port | default 9000 }}
        readinessProbe:
          httpGet:
            path: /readiness
            port: {{ (((.Values.services).indicators).health).port | default 9000 }}
        env:
        {{- include "common.env" "indicators" | indent 8 }}
        resources: {}
status: {}
