apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ticks
  name: ticks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticks
  strategy: {}
  template:
    metadata:
      annotations:
        {{if (.Values.debug).forceDeployment }}timestamp: {{ now | quote }}{{end}}
      labels:
        app: ticks
    spec:
      containers:
      - name: ticks
        image: {{ ((.Values.services).ticks).image.repository | default "lerenn/cryptellation-ticks" }}:{{ ((.Values.services).ticks).image.tag | default (printf "v%s" .Chart.AppVersion) }}
        imagePullPolicy: {{ ((.Values.services).ticks).image.pullPolicy | default "Always" }}
        livenessProbe:
          httpGet:
            path: /liveness
            port: {{ (((.Values.services).ticks).health).port | default 9000 }}
        readinessProbe:
          httpGet:
            path: /readiness
            port: {{ (((.Values.services).ticks).health).port | default 9000 }}
        env:
        - name: "BINANCE_API_KEY"
          valueFrom:
            configMapKeyRef:
              key: binance.api_key
              name: cryptellation-credentials
        - name: "BINANCE_SECRET_KEY"
          valueFrom:
            configMapKeyRef:
              key: binance.secret_key
              name: cryptellation-credentials
        {{- include "common.env" "ticks" | indent 8 }}
        resources: {}
status: {}
