################################################################################
# Dependencies
################################################################################

mongodb:
  enabled: true
  image:
    repository: zcube/bitnami-compat-mongodb
    tag: latest
  auth:
    enabled: false

nats:
  enabled: true

################################################################################
# Credentials
################################################################################

credentials:
  exchanges:
    binance:
      api_key:
      secret_key:
  opentelemetry:
    grpc:
      endpoint: lgtm-opentelemetry-collector.telemetry:4317

################################################################################
# Services
################################################################################

services:
  backtests:
    image:
      tag: devel
      pullPolicy: Never
  candlesticks:
    image:
      tag: devel
      pullPolicy: Never
  exchanges:
    image:
      tag: devel
      pullPolicy: Never
  forwardtests:
    image:
      tag: devel
      pullPolicy: Never
  indicators:
    image:
      tag: devel
      pullPolicy: Never
  ticks:
    image:
      tag: devel
      pullPolicy: Never

################################################################################
# Debug
################################################################################

debug:
  forceDeployment: true
