services:
  exchanges-sql:
    image: postgres:15.3
    networks:
      - cryptellation
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: exchanges
    expose:
      - "5432"
  exchanges-api:
    image: cosmtrek/air
    depends_on:
      - exchanges-sql
      - nats
      - uptrace-otelcollector
    networks:
      - cryptellation
    working_dir: /go/src/github.com/lerenn/cryptellation
    environment:
      DEV_MODE: true
      HEALTH_PORT: 9000
      NATS_HOST: nats
      NATS_PORT: 4222
      OPENTELEMETRY_GRPC_ENDPOINT: uptrace-otelcollector:4317
      SQLDB_HOST: exchanges-sql
      SQLDB_PORT: 5432
      SQLDB_USER: postgres
      SQLDB_PASSWORD: example
      SQLDB_DATABASE: exchanges
    env_file:
      - path: ../../../.credentials.env
        required: true
    command: [ "-c", "svc/exchanges/.air.toml" ]
    volumes:
      - gocache:/go/pkg/mod
      - gobuild:/root/.cache/go-build
      - ../../../:/go/src/github.com/lerenn/cryptellation
