version: 2.1
jobs:
  lint:
    docker:
      - image: golangci/golangci-lint:latest-alpine
    steps:
      - checkout
      - run: /bin/sh .make/lint/golang.sh

workflows:
  pre-tests:
    jobs:
      - lint
