version: "3.5"

services:
    redis:
        container_name: cryptellation-livetests-tests-redis
        image: redis:alpine
        hostname: redis
        networks:
            - cryptellation-livetests-tests-network
    tests:
        depends_on:
            - redis
        build: ./tests
        image: cryptellation-livetests-tests
        container_name: cryptellation-livetests-tests-instance
        env_file:
            - ../../.env
        environment:
            - REDIS_URL=redis:6379
        volumes:
            - gocache:/go/pkg/mod
            - gobuild:/root/.cache/go-build
            - .:/code
        networks:
            - cryptellation-livetests-tests-network

volumes:
    gocache:
    gobuild:

networks:
    cryptellation-livetests-tests-network:
