version: "3.5"

services:
    livetests-redis:
        image: redis:6-alpine
        networks:
            - cryptellation-network
    livetests:
        build:
            context: ../livetests
            dockerfile: build/package/Dockerfile
        image: "cryptellation/livetests:${DOCKER_IMAGE_TAG}"
        ports:
            - 127.0.0.1:9006:9006
        env_file:
            - ../../.services.env
            - ../../.credentials.env
        environment:
            - REDIS_URL=livetests-redis:6379
            - SERVICE_PORT=9006
        depends_on:
            - livetests-redis
            # - ticks
        networks:
            - cryptellation-network
    livetests-testing:
        profiles:
            - testing
        depends_on:
            - livetests-redis
        build: ./tests
        env_file:
            - ../../.services.env
            - ../../.credentials.env
        environment:
            - REDIS_URL=livetests-redis:6379
        volumes:
            - gocache:/go/pkg/mod
            - gobuild:/root/.cache/go-build
            - .:/code
        networks:
            - cryptellation-network

volumes:
    gocache:
    gobuild:

networks:
    cryptellation-network:
