include:
  - ../../../deployments/docker-compose/dependencies.docker-compose.yaml

services:
  ticks-api:
    image: cosmtrek/air
    depends_on:
      - nats
      - uptrace-otelcollector
    networks:
      - cryptellation
    working_dir: /go/src/github.com/lerenn/cryptellation
    environment:
      DEV_MODE: true
      HEALTH_PORT: 9000
      LOG_LEVEL: WARN
      MONGO_CONNECTION_STRING: mongodb://mongo:27017
      MONGO_DATABASE: cryptellation-ticks
      NATS_HOST: nats
      NATS_PORT: 4222
      OPENTELEMETRY_GRPC_ENDPOINT: uptrace-otelcollector:4317
    env_file:
      - path: ../../../.credentials.env
        required: true
    command: [ "-c", "svc/ticks/.air.toml" ]
    volumes:
      - gocache:/go/pkg/mod
      - gobuild:/root/.cache/go-build
      - ../../../:/go/src/github.com/lerenn/cryptellation
