{{- define "dependencies.cockroachdb.init-container" }}
{{- if .Values.cockroachdb.enabled }}
- name: cockroachdb-init-databases
  image: cockroachdb/cockroach:v22.2.2
  imagePullPolicy: IfNotPresent
  volumeMounts:
  - mountPath: /init
    name: cockroachdb-init-scripts-volume
  command:
  - sh
  - /init/entrypoint.sh
{{- end}}
{{- end}}

