version: "3.5"

services:
    candlesticks-cockroachdb:
        image: cockroachdb/cockroach
        # ports:
        #     - 26257:26257
        #     - 26256:8080
        networks:
            - network
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
        command: start-single-node --insecure
        restart: unless-stopped
        volumes:
            - ../../services/candlesticks/configs:/docker-entrypoint-initdb.d
    candlesticks:
        build:
            context: ../candlesticks
            dockerfile: build/package/Dockerfile
        image: "cryptellation/candlesticks:${DOCKER_IMAGE_TAG}"
        ports:
            - 127.0.0.1:9003:9003
        env_file:
            - ../../.env
        environment:
            - COCKROACHDB_HOST=candlesticks-cockroachdb
            - COCKROACHDB_DATABASE=candlesticks
            - SERVICE_PORT=9003
        depends_on:
            - candlesticks-cockroachdb
        networks:
            - network
    candlesticks-testing:
        profiles:
            - testing
        depends_on:
            - candlesticks-cockroachdb
        build: ./tests
        env_file:
            - ../../.env
        environment:
            - COCKROACHDB_HOST=candlesticks-cockroachdb
        volumes:
            - gocache:/go/pkg/mod
            - gobuild:/root/.cache/go-build
            - .:/code
        networks:
            - network

volumes:
    gocache:
    gobuild:

networks:
    network:
