version: "3.5"

services:
    redis:
        container_name: cryptellation-ticks-tests-redis
        image: redis:alpine
        hostname: redis
        networks:
            - cryptellation-ticks-tests-network
    nats:
        container_name: cryptellation-ticks-tests-nats
        image: nats:alpine
        hostname: nats
        networks:
            - cryptellation-ticks-tests-network
    tests:
        depends_on:
            - redis
            - nats
        build: ./tests
        image: cryptellation-ticks-tests
        container_name: cryptellation-ticks-tests-instance
        env_file:
            - ../../.env
        environment:
            - REDIS_URL=redis:6379
        volumes:
            - gocache:/go/pkg/mod
            - gobuild:/root/.cache/go-build
            - .:/code
        networks:
            - cryptellation-ticks-tests-network

volumes:
    gocache:
    gobuild:

networks:
    cryptellation-ticks-tests-network:
