version: "3.5"

services:
    ticks-redis:
        image: redis:6-alpine
        networks:
            - network
    nats:
        image: nats:alpine
        ports:
            - 4222:4222
        networks:
            - network
    ticks:
        build:
            context: ../ticks
            dockerfile: build/package/Dockerfile
        image: "cryptellation/ticks:${DOCKER_IMAGE_TAG}"
        ports:
            - 127.0.0.1:9005:9005
        env_file:
            - ../../.env
        environment:
            - REDIS_URL=ticks-redis:6379
            - SERVICE_PORT=9005
        depends_on:
            - ticks-redis
            - nats
        networks:
            - network
    ticks-testing:
        profiles:
            - testing
        depends_on:
            - ticks-redis
            - nats
        build: ./tests
        env_file:
            - ../../.env
        environment:
            - REDIS_URL=backtests-redis:6379
        volumes:
            - gocache:/go/pkg/mod
            - gobuild:/root/.cache/go-build
            - .:/code
        networks:
            - network

volumes:
    gocache:
    gobuild:

networks:
    network:
