include:
    - ../../tools/uptrace/docker-compose.yaml

services:
  mongo:
    image: mongo:7-jammy
    ports:
      - '27017:27017'
    expose:
      - '27017'
    networks:
      - cryptellation
  nats:
    image: nats
    ports:
      - 4222:4222
    networks:
      - cryptellation

volumes:
    gocache:
    gobuild:


networks:
    cryptellation: