apiVersion: batch/v1
kind: Job
metadata:
  name: init-databases
spec:
  parallelism: 1    
  completions: 1    
  template:         
    metadata:
      name: init-databases
    spec:
      volumes:
      - name: init-databases-scripts-volume
        configMap:
          name: init-databases-scripts
      containers:
      - name: init-databases
        image: cockroachdb/cockroach:v22.2.2
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /scripts
            name: init-databases-scripts-volume
        # TODO: avoid repeat fails until completion
        command:
          - ./cockroach
          - sql
          - --insecure
          - --host=cockroachdb-public.datastore
          - --file=/scripts/init-databases.sql
      restartPolicy: Never

