version: "3.5"

services:
    backtests-redis:
        image: redis:6-alpine
        networks:
            - cryptellation-network
    nats:
        image: nats:alpine
        ports:
            - 4222:4222
        networks:
            - cryptellation-network
    backtests:
        build:
            context: ../backtests
            dockerfile: build/package/Dockerfile
        image: "cryptellation/backtests:${DOCKER_IMAGE_TAG}"
        ports:
            - 127.0.0.1:9004:9004
        env_file:
            - ../../.services.env
            - ../../.credentials.env
        environment:
            - REDIS_URL=backtests-redis:6379
            - SERVICE_PORT=9004
        depends_on:
            - backtests-redis
            - nats
            # - candlesticks
        networks:
            - cryptellation-network
    backtests-testing:
        profiles:
            - testing
        depends_on:
            - backtests-redis
            - nats
        build: ./tests
        env_file:
            - ../../.services.env
            - ../../.credentials.env
        environment:
            - REDIS_URL=backtests-redis:6379
        volumes:
            - gocache:/go/pkg/mod
            - gobuild:/root/.cache/go-build
            - ./:/code
        networks:
            - cryptellation-network

volumes:
    gocache:
    gobuild:

networks:
    cryptellation-network:
