name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run linter
    if: |
      !startsWith(github.event.head_commit.message, 'release:')
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Create a go.work file
        run: cp go.work.example go.work
      - uses: dagger/dagger-for-github@v6.5.0
        with:
          verb: call
          args: -m build/ci lint --source-dir=. stdout 
  
  check-generation:
    name: Check generation has been run
    if: |
      !startsWith(github.event.head_commit.message, 'release:')
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Create a go.work file
        run: cp go.work.example go.work
      - uses: dagger/dagger-for-github@v6.5.0
        with:
          verb: call
          args: -m build/ci check-generation --source-dir=. stdout

  unit-tests:
    name: Run unit tests
    needs: ["lint", "check-generation"]
    if: |
      !startsWith(github.event.head_commit.message, 'release:')
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Create a go.work file
        run: cp go.work.example go.work
      - uses: dagger/dagger-for-github@v6.5.0
        with:
          verb: call
          args: -m build/ci unit-tests --source-dir=. stdout 

  # integration-tests:
  #   name: Run integration tests
  #   needs: ["unit-tests"]
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 5
  #   steps:
  #     - uses: actions/checkout@v4.1.1
  #     - name: Create a go.work file
  #       run: cp go.work.example go.work
  #     - name: Create a credentials file
  #       run: |
  #         echo "BINANCE_API_KEY=${{ secrets.BINANCE_API_KEY }}" > ./.credentials.env
  #         echo "BINANCE_SECRET_KEY=${{ secrets.BINANCE_SECRET_KEY }}" >> ./.credentials.env
  #     - uses: dagger/dagger-for-github@v6.5.0
  #       with:
  #         verb: call
  #         args: -m build/ci integration-tests --source-dir=. --secrets-file=file:./.credentials.env stdout 

  # end-to-end-tests:
  #   name: Run end-to-end tests
  #   needs: ["integration-tests"]
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 5
  #   steps:
  #     - uses: actions/checkout@v4.1.1
  #     - name: Create a go.work file
  #       run: cp go.work.example go.work
  #     - name: Create a credentials file
  #       run: |
  #         echo "BINANCE_API_KEY=${{ secrets.BINANCE_API_KEY }}" > ./.credentials.env
  #         echo "BINANCE_SECRET_KEY=${{ secrets.BINANCE_SECRET_KEY }}" >> ./.credentials.env
  #     - uses: dagger/dagger-for-github@v6.5.0
  #       with:
  #         verb: call
  #         args: -m build/ci end-to-end-tests --source-dir=. --secrets-file=file:./.credentials.env stdout 

  create-release:
    name: Create a release of the new version
    permissions:
      contents: write
    needs: ["unit-tests"]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: |
      github.ref == 'refs/heads/main' && 
      !startsWith(github.event.head_commit.message, 'release:')
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - uses: docker/login-action@v3
        with:
          username: lerenn
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Create a go.work file
        run: cp go.work.example go.work
      - uses: dagger/dagger-for-github@v6.5.0
        with:
          verb: call
          args: -m build/ci create-release --source-dir=. --ssh-private-key-file=env:SSH_PRIVATE_KEY --github-token=env:GITHUB_TOKEN
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-release:
    name: Publish the release of the new version
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: |
      github.ref == 'refs/heads/main' && 
      startsWith(github.event.head_commit.message, 'release:')
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - uses: docker/login-action@v3
        with:
          username: lerenn
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Create a go.work file
        run: cp go.work.example go.work
      - uses: dagger/dagger-for-github@v6.5.0
        with:
          verb: call
          args: -m build/ci publish-release --source-dir=. --ssh-private-key-file=env:SSH_PRIVATE_KEY
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
